/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package workshoppackage;

import Dialog.cache;
import db.Database;
import java.awt.Color;
import java.io.File;
import java.io.FileNotFoundException;
import java.io.FileOutputStream;
import java.io.IOException;
import java.sql.ResultSet;
import java.text.DateFormat;
import java.text.SimpleDateFormat;
import java.time.LocalDateTime;
import java.time.format.DateTimeFormatter;
import java.util.Date;
import java.util.Vector;
import javafx.scene.control.Cell;
import javax.swing.BorderFactory;
import javax.swing.JFileChooser;
import javax.swing.JLabel;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Oshan Premachandra
 */
public class Clients extends javax.swing.JFrame {

    /**
     * Creates new form Clients
     */
    
    DateFormat pfm = new SimpleDateFormat("yyyy-MM-dd HH:mm:ss");
    
    private static DefaultTableModel dtm;
    
    JLabel [] labels;
    JPanel [] panels;
    boolean pressed = false;
    
    public Clients() {
        initComponents();
        addLabelToTable();
        TopNavPanel.hide();
        GetToday();
                
        LogUserNameLbl.setText("Welcome "+cache.LogUserName);
        
        dtm = (DefaultTableModel) ClientsTbl.getModel();
        LoadClientData();
    }
    
    public void addLabelToTable(){
        labels = new JLabel[]{HomeLbl,LogoutLbl};
        panels = new JPanel[]{JobBtn,InventoryBtn,BookingsBtn,ClientsBtn,SupplierBtn,VehicleBtn,StockBtn,InventoryBtn,EstimatesBtn,PartSalesBtn,PartsOrderBtn,SettingsBtn,SystemServiceBtn};
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        LogoutLbl = new javax.swing.JLabel();
        HomeLbl = new javax.swing.JLabel();
        MenuLbl = new javax.swing.JLabel();
        LogUserNameLbl = new javax.swing.JLabel();
        NowDateLbl = new javax.swing.JLabel();
        TopNavPanel = new javax.swing.JPanel();
        JobBtn = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        InventoryBtn = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        BookingsBtn = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        ClientsBtn = new javax.swing.JPanel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        SupplierBtn = new javax.swing.JPanel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        VehicleBtn = new javax.swing.JPanel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        StockBtn = new javax.swing.JPanel();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        InvoicesBtn = new javax.swing.JPanel();
        jLabel15 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        EstimatesBtn = new javax.swing.JPanel();
        jLabel17 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        PartSalesBtn = new javax.swing.JPanel();
        jLabel19 = new javax.swing.JLabel();
        jLabel20 = new javax.swing.JLabel();
        PartsOrderBtn = new javax.swing.JPanel();
        jLabel21 = new javax.swing.JLabel();
        jLabel22 = new javax.swing.JLabel();
        SettingsBtn = new javax.swing.JPanel();
        jLabel23 = new javax.swing.JLabel();
        jLabel24 = new javax.swing.JLabel();
        SystemServiceBtn = new javax.swing.JPanel();
        jLabel25 = new javax.swing.JLabel();
        jLabel26 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        jLabel27 = new javax.swing.JLabel();
        jPanel4 = new javax.swing.JPanel();
        jLabel28 = new javax.swing.JLabel();
        CustomerNameField = new javax.swing.JTextField();
        jLabel29 = new javax.swing.JLabel();
        PhoneField = new javax.swing.JTextField();
        jLabel30 = new javax.swing.JLabel();
        AddressField = new javax.swing.JTextField();
        jLabel31 = new javax.swing.JLabel();
        EmailField = new javax.swing.JTextField();
        jLabel32 = new javax.swing.JLabel();
        jLabel33 = new javax.swing.JLabel();
        jLabel34 = new javax.swing.JLabel();
        DateField = new javax.swing.JTextField();
        jLabel35 = new javax.swing.JLabel();
        SelectHowtoKnow = new javax.swing.JComboBox<>();
        SelectBirthDate = new javax.swing.JComboBox<>();
        SelectBirthMonth = new javax.swing.JComboBox<>();
        RegisterClientBtn = new javax.swing.JButton();
        UpdateClientBtn = new javax.swing.JButton();
        jLabel36 = new javax.swing.JLabel();
        jPanel5 = new javax.swing.JPanel();
        jScrollPane3 = new javax.swing.JScrollPane();
        ClientsTbl = new javax.swing.JTable();
        jLabel37 = new javax.swing.JLabel();
        SearchAreaLbl = new javax.swing.JTextField();
        SearchBtn = new javax.swing.JButton();
        ClearBtn = new javax.swing.JButton();
        ExcelExportBtn = new javax.swing.JButton();
        jLabel38 = new javax.swing.JLabel();
        ClientidField = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(1024, 768));
        setPreferredSize(new java.awt.Dimension(1400, 900));

        jScrollPane1.setMinimumSize(new java.awt.Dimension(1024, 768));
        jScrollPane1.setPreferredSize(new java.awt.Dimension(1024, 768));

        jPanel2.setBackground(new java.awt.Color(0, 87, 120));

        LogoutLbl.setBackground(new java.awt.Color(0, 87, 120));
        LogoutLbl.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        LogoutLbl.setIcon(new javax.swing.ImageIcon(getClass().getResource("/assets/logout.png"))); // NOI18N
        LogoutLbl.setOpaque(true);
        LogoutLbl.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                LogoutLblMouseMoved(evt);
            }
        });
        LogoutLbl.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                LogoutLblMouseClicked(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                LogoutLblMouseExited(evt);
            }
        });

        HomeLbl.setBackground(new java.awt.Color(0, 87, 120));
        HomeLbl.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        HomeLbl.setIcon(new javax.swing.ImageIcon(getClass().getResource("/assets/home.png"))); // NOI18N
        HomeLbl.setOpaque(true);
        HomeLbl.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                HomeLblMouseMoved(evt);
            }
        });
        HomeLbl.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseExited(java.awt.event.MouseEvent evt) {
                HomeLblMouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                HomeLblMousePressed(evt);
            }
        });

        MenuLbl.setBackground(new java.awt.Color(0, 87, 120));
        MenuLbl.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        MenuLbl.setIcon(new javax.swing.ImageIcon(getClass().getResource("/assets/menu.png"))); // NOI18N
        MenuLbl.setOpaque(true);
        MenuLbl.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                MenuLblMouseMoved(evt);
            }
        });
        MenuLbl.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseExited(java.awt.event.MouseEvent evt) {
                MenuLblMouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                MenuLblMousePressed(evt);
            }
        });

        LogUserNameLbl.setFont(new java.awt.Font("Calibri", 1, 14)); // NOI18N
        LogUserNameLbl.setForeground(new java.awt.Color(255, 255, 255));
        LogUserNameLbl.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);

        NowDateLbl.setFont(new java.awt.Font("Calibri", 1, 14)); // NOI18N
        NowDateLbl.setForeground(new java.awt.Color(255, 255, 255));
        NowDateLbl.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(59, 59, 59)
                .addComponent(HomeLbl, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(LogUserNameLbl, javax.swing.GroupLayout.PREFERRED_SIZE, 320, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(310, 310, 310)
                .addComponent(NowDateLbl, javax.swing.GroupLayout.PREFERRED_SIZE, 158, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(LogoutLbl, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(19, 19, 19))
            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel2Layout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(MenuLbl, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(972, Short.MAX_VALUE)))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(HomeLbl, javax.swing.GroupLayout.DEFAULT_SIZE, 46, Short.MAX_VALUE)
            .addComponent(LogoutLbl, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(LogUserNameLbl, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(NowDateLbl, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(MenuLbl, javax.swing.GroupLayout.DEFAULT_SIZE, 46, Short.MAX_VALUE))
        );

        TopNavPanel.setBackground(new java.awt.Color(0, 120, 167));

        JobBtn.setBackground(new java.awt.Color(0, 120, 167));
        JobBtn.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                JobBtnMouseMoved(evt);
            }
        });
        JobBtn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                JobBtnMouseClicked(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                JobBtnMouseExited(evt);
            }
        });

        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/assets/jobs.png"))); // NOI18N

        jLabel2.setFont(new java.awt.Font("Calibri", 1, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("Jobs");

        javax.swing.GroupLayout JobBtnLayout = new javax.swing.GroupLayout(JobBtn);
        JobBtn.setLayout(JobBtnLayout);
        JobBtnLayout.setHorizontalGroup(
            JobBtnLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, 125, Short.MAX_VALUE)
        );
        JobBtnLayout.setVerticalGroup(
            JobBtnLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(JobBtnLayout.createSequentialGroup()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        InventoryBtn.setBackground(new java.awt.Color(0, 120, 167));
        InventoryBtn.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                InventoryBtnMouseMoved(evt);
            }
        });
        InventoryBtn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                InventoryBtnMouseClicked(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                InventoryBtnMouseExited(evt);
            }
        });

        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/assets/inventory.png"))); // NOI18N

        jLabel4.setFont(new java.awt.Font("Calibri", 1, 18)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel4.setText("Inventory");

        javax.swing.GroupLayout InventoryBtnLayout = new javax.swing.GroupLayout(InventoryBtn);
        InventoryBtn.setLayout(InventoryBtnLayout);
        InventoryBtnLayout.setHorizontalGroup(
            InventoryBtnLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jLabel4, javax.swing.GroupLayout.DEFAULT_SIZE, 125, Short.MAX_VALUE)
        );
        InventoryBtnLayout.setVerticalGroup(
            InventoryBtnLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(InventoryBtnLayout.createSequentialGroup()
                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        BookingsBtn.setBackground(new java.awt.Color(0, 120, 167));
        BookingsBtn.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                BookingsBtnMouseMoved(evt);
            }
        });
        BookingsBtn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                BookingsBtnMouseClicked(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                BookingsBtnMouseExited(evt);
            }
        });

        jLabel5.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/assets/bookings.png"))); // NOI18N

        jLabel6.setFont(new java.awt.Font("Calibri", 1, 18)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel6.setText("Bookings");

        javax.swing.GroupLayout BookingsBtnLayout = new javax.swing.GroupLayout(BookingsBtn);
        BookingsBtn.setLayout(BookingsBtnLayout);
        BookingsBtnLayout.setHorizontalGroup(
            BookingsBtnLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jLabel6, javax.swing.GroupLayout.DEFAULT_SIZE, 125, Short.MAX_VALUE)
        );
        BookingsBtnLayout.setVerticalGroup(
            BookingsBtnLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(BookingsBtnLayout.createSequentialGroup()
                .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        ClientsBtn.setBackground(new java.awt.Color(0, 120, 167));
        ClientsBtn.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                ClientsBtnMouseMoved(evt);
            }
        });
        ClientsBtn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                ClientsBtnMouseClicked(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                ClientsBtnMouseExited(evt);
            }
        });

        jLabel7.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/assets/clients.png"))); // NOI18N

        jLabel8.setFont(new java.awt.Font("Calibri", 1, 18)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(255, 255, 255));
        jLabel8.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel8.setText("Clients");

        javax.swing.GroupLayout ClientsBtnLayout = new javax.swing.GroupLayout(ClientsBtn);
        ClientsBtn.setLayout(ClientsBtnLayout);
        ClientsBtnLayout.setHorizontalGroup(
            ClientsBtnLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jLabel8, javax.swing.GroupLayout.DEFAULT_SIZE, 125, Short.MAX_VALUE)
        );
        ClientsBtnLayout.setVerticalGroup(
            ClientsBtnLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(ClientsBtnLayout.createSequentialGroup()
                .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        SupplierBtn.setBackground(new java.awt.Color(0, 120, 167));
        SupplierBtn.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                SupplierBtnMouseMoved(evt);
            }
        });
        SupplierBtn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                SupplierBtnMouseClicked(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                SupplierBtnMouseExited(evt);
            }
        });

        jLabel9.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel9.setIcon(new javax.swing.ImageIcon(getClass().getResource("/assets/suppliers.png"))); // NOI18N

        jLabel10.setFont(new java.awt.Font("Calibri", 1, 18)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(255, 255, 255));
        jLabel10.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel10.setText("Suppliers");

        javax.swing.GroupLayout SupplierBtnLayout = new javax.swing.GroupLayout(SupplierBtn);
        SupplierBtn.setLayout(SupplierBtnLayout);
        SupplierBtnLayout.setHorizontalGroup(
            SupplierBtnLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel9, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jLabel10, javax.swing.GroupLayout.DEFAULT_SIZE, 125, Short.MAX_VALUE)
        );
        SupplierBtnLayout.setVerticalGroup(
            SupplierBtnLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(SupplierBtnLayout.createSequentialGroup()
                .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel10, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        VehicleBtn.setBackground(new java.awt.Color(0, 120, 167));
        VehicleBtn.setPreferredSize(new java.awt.Dimension(125, 89));
        VehicleBtn.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                VehicleBtnMouseMoved(evt);
            }
        });
        VehicleBtn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                VehicleBtnMouseClicked(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                VehicleBtnMouseExited(evt);
            }
        });

        jLabel11.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel11.setIcon(new javax.swing.ImageIcon(getClass().getResource("/assets/vehicle.png"))); // NOI18N

        jLabel12.setFont(new java.awt.Font("Calibri", 1, 18)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(255, 255, 255));
        jLabel12.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel12.setText("Vehicle");

        javax.swing.GroupLayout VehicleBtnLayout = new javax.swing.GroupLayout(VehicleBtn);
        VehicleBtn.setLayout(VehicleBtnLayout);
        VehicleBtnLayout.setHorizontalGroup(
            VehicleBtnLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel11, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jLabel12, javax.swing.GroupLayout.DEFAULT_SIZE, 125, Short.MAX_VALUE)
        );
        VehicleBtnLayout.setVerticalGroup(
            VehicleBtnLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(VehicleBtnLayout.createSequentialGroup()
                .addComponent(jLabel11, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel12, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        StockBtn.setBackground(new java.awt.Color(0, 120, 167));
        StockBtn.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                StockBtnMouseMoved(evt);
            }
        });
        StockBtn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                StockBtnMouseClicked(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                StockBtnMouseExited(evt);
            }
        });

        jLabel13.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel13.setIcon(new javax.swing.ImageIcon(getClass().getResource("/assets/stock.png"))); // NOI18N

        jLabel14.setFont(new java.awt.Font("Calibri", 1, 18)); // NOI18N
        jLabel14.setForeground(new java.awt.Color(255, 255, 255));
        jLabel14.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel14.setText("Stock");

        javax.swing.GroupLayout StockBtnLayout = new javax.swing.GroupLayout(StockBtn);
        StockBtn.setLayout(StockBtnLayout);
        StockBtnLayout.setHorizontalGroup(
            StockBtnLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel13, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jLabel14, javax.swing.GroupLayout.DEFAULT_SIZE, 125, Short.MAX_VALUE)
        );
        StockBtnLayout.setVerticalGroup(
            StockBtnLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(StockBtnLayout.createSequentialGroup()
                .addComponent(jLabel13, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel14, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        InvoicesBtn.setBackground(new java.awt.Color(0, 120, 167));
        InvoicesBtn.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                InvoicesBtnMouseMoved(evt);
            }
        });
        InvoicesBtn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                InvoicesBtnMouseClicked(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                InvoicesBtnMouseExited(evt);
            }
        });

        jLabel15.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel15.setIcon(new javax.swing.ImageIcon(getClass().getResource("/assets/invoice.png"))); // NOI18N

        jLabel16.setFont(new java.awt.Font("Calibri", 1, 18)); // NOI18N
        jLabel16.setForeground(new java.awt.Color(255, 255, 255));
        jLabel16.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel16.setText("Invoices");

        javax.swing.GroupLayout InvoicesBtnLayout = new javax.swing.GroupLayout(InvoicesBtn);
        InvoicesBtn.setLayout(InvoicesBtnLayout);
        InvoicesBtnLayout.setHorizontalGroup(
            InvoicesBtnLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel15, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jLabel16, javax.swing.GroupLayout.DEFAULT_SIZE, 125, Short.MAX_VALUE)
        );
        InvoicesBtnLayout.setVerticalGroup(
            InvoicesBtnLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(InvoicesBtnLayout.createSequentialGroup()
                .addComponent(jLabel15, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel16, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        EstimatesBtn.setBackground(new java.awt.Color(0, 120, 167));
        EstimatesBtn.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                EstimatesBtnMouseMoved(evt);
            }
        });
        EstimatesBtn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                EstimatesBtnMouseClicked(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                EstimatesBtnMouseExited(evt);
            }
        });

        jLabel17.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel17.setIcon(new javax.swing.ImageIcon(getClass().getResource("/assets/estimate.png"))); // NOI18N

        jLabel18.setFont(new java.awt.Font("Calibri", 1, 18)); // NOI18N
        jLabel18.setForeground(new java.awt.Color(255, 255, 255));
        jLabel18.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel18.setText("Estimates");

        javax.swing.GroupLayout EstimatesBtnLayout = new javax.swing.GroupLayout(EstimatesBtn);
        EstimatesBtn.setLayout(EstimatesBtnLayout);
        EstimatesBtnLayout.setHorizontalGroup(
            EstimatesBtnLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel17, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jLabel18, javax.swing.GroupLayout.DEFAULT_SIZE, 125, Short.MAX_VALUE)
        );
        EstimatesBtnLayout.setVerticalGroup(
            EstimatesBtnLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(EstimatesBtnLayout.createSequentialGroup()
                .addComponent(jLabel17, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel18, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        PartSalesBtn.setBackground(new java.awt.Color(0, 120, 167));
        PartSalesBtn.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                PartSalesBtnMouseMoved(evt);
            }
        });
        PartSalesBtn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                PartSalesBtnMouseClicked(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                PartSalesBtnMouseExited(evt);
            }
        });

        jLabel19.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel19.setIcon(new javax.swing.ImageIcon(getClass().getResource("/assets/invoice.png"))); // NOI18N

        jLabel20.setFont(new java.awt.Font("Calibri", 1, 18)); // NOI18N
        jLabel20.setForeground(new java.awt.Color(255, 255, 255));
        jLabel20.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel20.setText("Part Sale");

        javax.swing.GroupLayout PartSalesBtnLayout = new javax.swing.GroupLayout(PartSalesBtn);
        PartSalesBtn.setLayout(PartSalesBtnLayout);
        PartSalesBtnLayout.setHorizontalGroup(
            PartSalesBtnLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel19, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jLabel20, javax.swing.GroupLayout.DEFAULT_SIZE, 125, Short.MAX_VALUE)
        );
        PartSalesBtnLayout.setVerticalGroup(
            PartSalesBtnLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PartSalesBtnLayout.createSequentialGroup()
                .addComponent(jLabel19, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel20, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        PartsOrderBtn.setBackground(new java.awt.Color(0, 120, 167));
        PartsOrderBtn.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                PartsOrderBtnMouseMoved(evt);
            }
        });
        PartsOrderBtn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                PartsOrderBtnMouseClicked(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                PartsOrderBtnMouseExited(evt);
            }
        });

        jLabel21.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel21.setIcon(new javax.swing.ImageIcon(getClass().getResource("/assets/partorder.png"))); // NOI18N

        jLabel22.setFont(new java.awt.Font("Calibri", 1, 18)); // NOI18N
        jLabel22.setForeground(new java.awt.Color(255, 255, 255));
        jLabel22.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel22.setText("Parts Order");

        javax.swing.GroupLayout PartsOrderBtnLayout = new javax.swing.GroupLayout(PartsOrderBtn);
        PartsOrderBtn.setLayout(PartsOrderBtnLayout);
        PartsOrderBtnLayout.setHorizontalGroup(
            PartsOrderBtnLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel21, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jLabel22, javax.swing.GroupLayout.DEFAULT_SIZE, 125, Short.MAX_VALUE)
        );
        PartsOrderBtnLayout.setVerticalGroup(
            PartsOrderBtnLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PartsOrderBtnLayout.createSequentialGroup()
                .addComponent(jLabel21, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel22, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        SettingsBtn.setBackground(new java.awt.Color(0, 120, 167));
        SettingsBtn.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                SettingsBtnMouseMoved(evt);
            }
        });
        SettingsBtn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                SettingsBtnMouseClicked(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                SettingsBtnMouseExited(evt);
            }
        });

        jLabel23.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel23.setIcon(new javax.swing.ImageIcon(getClass().getResource("/assets/settings.png"))); // NOI18N

        jLabel24.setFont(new java.awt.Font("Calibri", 1, 18)); // NOI18N
        jLabel24.setForeground(new java.awt.Color(255, 255, 255));
        jLabel24.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel24.setText("Settings");

        javax.swing.GroupLayout SettingsBtnLayout = new javax.swing.GroupLayout(SettingsBtn);
        SettingsBtn.setLayout(SettingsBtnLayout);
        SettingsBtnLayout.setHorizontalGroup(
            SettingsBtnLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel23, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jLabel24, javax.swing.GroupLayout.DEFAULT_SIZE, 125, Short.MAX_VALUE)
        );
        SettingsBtnLayout.setVerticalGroup(
            SettingsBtnLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(SettingsBtnLayout.createSequentialGroup()
                .addComponent(jLabel23, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel24, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        SystemServiceBtn.setBackground(new java.awt.Color(0, 120, 167));
        SystemServiceBtn.setPreferredSize(new java.awt.Dimension(125, 89));
        SystemServiceBtn.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                SystemServiceBtnMouseMoved(evt);
            }
        });
        SystemServiceBtn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                SystemServiceBtnMouseClicked(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                SystemServiceBtnMouseExited(evt);
            }
        });

        jLabel25.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel25.setIcon(new javax.swing.ImageIcon(getClass().getResource("/assets/systemservice.png"))); // NOI18N

        jLabel26.setFont(new java.awt.Font("Calibri", 1, 18)); // NOI18N
        jLabel26.setForeground(new java.awt.Color(255, 255, 255));
        jLabel26.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel26.setText("System Services");

        javax.swing.GroupLayout SystemServiceBtnLayout = new javax.swing.GroupLayout(SystemServiceBtn);
        SystemServiceBtn.setLayout(SystemServiceBtnLayout);
        SystemServiceBtnLayout.setHorizontalGroup(
            SystemServiceBtnLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel25, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jLabel26, javax.swing.GroupLayout.DEFAULT_SIZE, 125, Short.MAX_VALUE)
        );
        SystemServiceBtnLayout.setVerticalGroup(
            SystemServiceBtnLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(SystemServiceBtnLayout.createSequentialGroup()
                .addComponent(jLabel25, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel26, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout TopNavPanelLayout = new javax.swing.GroupLayout(TopNavPanel);
        TopNavPanel.setLayout(TopNavPanelLayout);
        TopNavPanelLayout.setHorizontalGroup(
            TopNavPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(TopNavPanelLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(TopNavPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(TopNavPanelLayout.createSequentialGroup()
                        .addComponent(InvoicesBtn, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(EstimatesBtn, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(PartSalesBtn, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(PartsOrderBtn, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(SettingsBtn, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(SystemServiceBtn, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(143, 143, 143))
                    .addGroup(TopNavPanelLayout.createSequentialGroup()
                        .addComponent(JobBtn, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(InventoryBtn, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(BookingsBtn, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(ClientsBtn, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(SupplierBtn, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(VehicleBtn, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(StockBtn, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        TopNavPanelLayout.setVerticalGroup(
            TopNavPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(TopNavPanelLayout.createSequentialGroup()
                .addGroup(TopNavPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(JobBtn, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(InventoryBtn, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(BookingsBtn, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(ClientsBtn, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(SupplierBtn, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(VehicleBtn, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(StockBtn, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(TopNavPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(InvoicesBtn, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(EstimatesBtn, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(PartSalesBtn, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(PartsOrderBtn, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(SettingsBtn, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(SystemServiceBtn, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel3.setBackground(new java.awt.Color(0, 120, 167));

        jLabel27.setFont(new java.awt.Font("Calibri", 1, 24)); // NOI18N
        jLabel27.setForeground(new java.awt.Color(255, 255, 255));
        jLabel27.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel27.setText("Clients");

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel27, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel27, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 36, Short.MAX_VALUE)
        );

        jPanel4.setBackground(new java.awt.Color(255, 255, 255));

        jLabel28.setFont(new java.awt.Font("Calibri", 1, 14)); // NOI18N
        jLabel28.setText("Customer Or Company Name");

        CustomerNameField.setFont(new java.awt.Font("Calibri", 1, 14)); // NOI18N

        jLabel29.setFont(new java.awt.Font("Calibri", 1, 14)); // NOI18N
        jLabel29.setText("Date");

        PhoneField.setFont(new java.awt.Font("Calibri", 1, 14)); // NOI18N

        jLabel30.setFont(new java.awt.Font("Calibri", 1, 14)); // NOI18N
        jLabel30.setText("Address");

        AddressField.setFont(new java.awt.Font("Calibri", 1, 14)); // NOI18N

        jLabel31.setFont(new java.awt.Font("Calibri", 1, 14)); // NOI18N
        jLabel31.setText("Email Address");

        EmailField.setFont(new java.awt.Font("Calibri", 1, 14)); // NOI18N
        EmailField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                EmailFieldActionPerformed(evt);
            }
        });

        jLabel32.setFont(new java.awt.Font("Calibri", 1, 14)); // NOI18N
        jLabel32.setText("Telephone No.");

        jLabel33.setFont(new java.awt.Font("Calibri", 1, 14)); // NOI18N
        jLabel33.setText("Birthday Month");

        jLabel34.setFont(new java.awt.Font("Calibri", 1, 14)); // NOI18N
        jLabel34.setText("Birthday Date");

        DateField.setFont(new java.awt.Font("Calibri", 1, 14)); // NOI18N

        jLabel35.setFont(new java.awt.Font("Calibri", 1, 14)); // NOI18N
        jLabel35.setText("How did they hear about us?");

        SelectHowtoKnow.setFont(new java.awt.Font("Calibri", 1, 14)); // NOI18N
        SelectHowtoKnow.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Friend", "Facebook", "Instergram", "News Paper", "Other Website", "Other" }));
        SelectHowtoKnow.setPreferredSize(new java.awt.Dimension(6, 23));

        SelectBirthDate.setFont(new java.awt.Font("Calibri", 1, 14)); // NOI18N
        SelectBirthDate.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "01", "02", "03", "04", "05", "06", "07", "08", "09", "10", "11", "12", "13", "14", "15", "16", "17", "18", "19", "20", "21", "22", "23", "24", "25", "26", "27", "28", "29", "30", "31" }));

        SelectBirthMonth.setFont(new java.awt.Font("Calibri", 1, 14)); // NOI18N
        SelectBirthMonth.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "January", "February", "March", "April", "May", "June", "July", "August", "September", "Octomber", "November", "December" }));

        RegisterClientBtn.setBackground(new java.awt.Color(255, 255, 255));
        RegisterClientBtn.setFont(new java.awt.Font("Calibri", 1, 14)); // NOI18N
        RegisterClientBtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/assets/add.png"))); // NOI18N
        RegisterClientBtn.setText("Register Client");
        RegisterClientBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                RegisterClientBtnActionPerformed(evt);
            }
        });

        UpdateClientBtn.setBackground(new java.awt.Color(255, 255, 255));
        UpdateClientBtn.setFont(new java.awt.Font("Calibri", 1, 14)); // NOI18N
        UpdateClientBtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/assets/update.png"))); // NOI18N
        UpdateClientBtn.setText("Update Client");
        UpdateClientBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                UpdateClientBtnActionPerformed(evt);
            }
        });

        jPanel5.setBackground(new java.awt.Color(255, 255, 255));

        ClientsTbl.setFont(new java.awt.Font("Calibri", 1, 14)); // NOI18N
        ClientsTbl.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null}
            },
            new String [] {
                "#", "Customer Name Or Company Name", "Email", "Birthday", "Phone Number", "Registartion Date", "Address", "Howknow"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        ClientsTbl.setRowHeight(25);
        ClientsTbl.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                ClientsTblMouseClicked(evt);
            }
        });
        jScrollPane3.setViewportView(ClientsTbl);
        if (ClientsTbl.getColumnModel().getColumnCount() > 0) {
            ClientsTbl.getColumnModel().getColumn(0).setMinWidth(50);
            ClientsTbl.getColumnModel().getColumn(0).setPreferredWidth(50);
            ClientsTbl.getColumnModel().getColumn(0).setMaxWidth(50);
            ClientsTbl.getColumnModel().getColumn(6).setMinWidth(0);
            ClientsTbl.getColumnModel().getColumn(6).setPreferredWidth(0);
            ClientsTbl.getColumnModel().getColumn(6).setMaxWidth(0);
            ClientsTbl.getColumnModel().getColumn(7).setMinWidth(0);
            ClientsTbl.getColumnModel().getColumn(7).setPreferredWidth(0);
            ClientsTbl.getColumnModel().getColumn(7).setMaxWidth(0);
        }

        jLabel37.setFont(new java.awt.Font("Calibri", 1, 18)); // NOI18N
        jLabel37.setText("Client List");

        SearchAreaLbl.setFont(new java.awt.Font("Calibri", 1, 14)); // NOI18N
        SearchAreaLbl.setPreferredSize(new java.awt.Dimension(6, 28));
        SearchAreaLbl.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SearchAreaLblActionPerformed(evt);
            }
        });

        SearchBtn.setBackground(new java.awt.Color(255, 255, 255));
        SearchBtn.setFont(new java.awt.Font("Calibri", 1, 14)); // NOI18N
        SearchBtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/assets/search.png"))); // NOI18N
        SearchBtn.setText("Search");

        ClearBtn.setBackground(new java.awt.Color(255, 255, 255));
        ClearBtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/assets/clear.png"))); // NOI18N
        ClearBtn.setMaximumSize(new java.awt.Dimension(101, 33));
        ClearBtn.setMinimumSize(new java.awt.Dimension(101, 33));
        ClearBtn.setPreferredSize(new java.awt.Dimension(101, 33));

        ExcelExportBtn.setBackground(new java.awt.Color(255, 255, 255));
        ExcelExportBtn.setFont(new java.awt.Font("Calibri", 1, 14)); // NOI18N
        ExcelExportBtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/assets/xls.png"))); // NOI18N
        ExcelExportBtn.setText("Excel");
        ExcelExportBtn.setMaximumSize(new java.awt.Dimension(101, 33));
        ExcelExportBtn.setMinimumSize(new java.awt.Dimension(101, 33));
        ExcelExportBtn.setPreferredSize(new java.awt.Dimension(101, 33));
        ExcelExportBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ExcelExportBtnActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane3)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel5Layout.createSequentialGroup()
                        .addComponent(ExcelExportBtn, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(SearchAreaLbl, javax.swing.GroupLayout.PREFERRED_SIZE, 243, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(SearchBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(5, 5, 5)
                        .addComponent(ClearBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jLabel37, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addGap(11, 11, 11)
                .addComponent(jLabel37, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(ClearBtn, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(SearchBtn, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(ExcelExportBtn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(SearchAreaLbl, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 378, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(14, Short.MAX_VALUE))
        );

        jLabel38.setFont(new java.awt.Font("Calibri", 1, 18)); // NOI18N
        jLabel38.setText("Client Form");

        ClientidField.setForeground(new java.awt.Color(255, 255, 255));

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel28, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(CustomerNameField)
                    .addComponent(jLabel30, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(AddressField)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addComponent(PhoneField, javax.swing.GroupLayout.PREFERRED_SIZE, 670, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(EmailField))
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addComponent(jLabel32, javax.swing.GroupLayout.PREFERRED_SIZE, 670, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel31, javax.swing.GroupLayout.PREFERRED_SIZE, 674, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jLabel29, javax.swing.GroupLayout.DEFAULT_SIZE, 406, Short.MAX_VALUE)
                            .addComponent(DateField))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jLabel33, javax.swing.GroupLayout.PREFERRED_SIZE, 254, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(SelectBirthMonth, 0, 258, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(SelectBirthDate, javax.swing.GroupLayout.PREFERRED_SIZE, 276, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel34, javax.swing.GroupLayout.PREFERRED_SIZE, 276, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(SelectHowtoKnow, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel35, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                        .addComponent(jLabel36, javax.swing.GroupLayout.PREFERRED_SIZE, 969, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(8, 8, 8)
                        .addComponent(ClientidField, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(UpdateClientBtn)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(RegisterClientBtn))
                    .addComponent(jLabel38, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel38, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel28, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(CustomerNameField, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel30, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(AddressField, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel31, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel32, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(PhoneField, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(EmailField, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel29, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel33, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel34, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel35, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(DateField, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(SelectHowtoKnow, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(SelectBirthDate, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(SelectBirthMonth, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(RegisterClientBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(UpdateClientBtn))
                    .addComponent(jLabel36, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(ClientidField, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(23, 23, 23)
                .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(TopNavPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(TopNavPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(279, Short.MAX_VALUE))
        );

        jScrollPane1.setViewportView(jPanel1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void GetToday(){
        
        DateTimeFormatter dtf = DateTimeFormatter.ofPattern("dd MMMM yyyy");
        LocalDateTime now = LocalDateTime.now();
        
        DateTimeFormatter rd = DateTimeFormatter.ofPattern("yyyy-MM-dd");
        
        NowDateLbl.setText(dtf.format(now));
        DateField.setText(rd.format(now));
    }
    
    public void LoadClientData(){
        ResultSet cd = Database.getData("SELECT * FROM tbl_client ORDER BY client_id DESC ");
        dtm.setRowCount(0);
        try {
            while(cd.next()){
                
                Vector v = new Vector();
                v.add(cd.getInt(1));
                v.add(cd.getString(2));
                v.add(cd.getString(3));
                v.add(cd.getString(5));
                
                v.add(cd.getString(6));
                v.add(cd.getString(4));
                
                v.add(cd.getString(8));
                v.add(cd.getString(7));
                
                dtm.addRow(v);
            }
        }catch(Exception ex){
            ex.printStackTrace();
        }
    }
    
    private void LogoutLblMouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_LogoutLblMouseMoved
        setLabelBackground(LogoutLbl);
    }//GEN-LAST:event_LogoutLblMouseMoved

    private void LogoutLblMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_LogoutLblMouseClicked
        new Login().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_LogoutLblMouseClicked

    private void LogoutLblMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_LogoutLblMouseExited
        resetLabelBackground(LogoutLbl);
    }//GEN-LAST:event_LogoutLblMouseExited

    private void HomeLblMouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_HomeLblMouseMoved
        setLabelBackground(HomeLbl);
    }//GEN-LAST:event_HomeLblMouseMoved

    private void HomeLblMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_HomeLblMouseExited
        resetLabelBackground(HomeLbl);
    }//GEN-LAST:event_HomeLblMouseExited

    private void HomeLblMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_HomeLblMousePressed
        new Home().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_HomeLblMousePressed

    private void MenuLblMouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_MenuLblMouseMoved
        setLabelBackground(MenuLbl);
    }//GEN-LAST:event_MenuLblMouseMoved

    private void MenuLblMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_MenuLblMouseExited
        resetLabelBackground(MenuLbl);
    }//GEN-LAST:event_MenuLblMouseExited

    private void MenuLblMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_MenuLblMousePressed
        if(pressed){
            TopNavPanel.setVisible(false);
            pressed = false;
        }else{
            TopNavPanel.setVisible(true);
            pressed = true;
        }
    }//GEN-LAST:event_MenuLblMousePressed

    private void JobBtnMouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_JobBtnMouseMoved
        setPanelBackground(JobBtn);
    }//GEN-LAST:event_JobBtnMouseMoved

    private void JobBtnMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_JobBtnMouseClicked
        new JobNav().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_JobBtnMouseClicked

    private void JobBtnMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_JobBtnMouseExited
        resetPanelBackground(JobBtn);
    }//GEN-LAST:event_JobBtnMouseExited

    private void InventoryBtnMouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_InventoryBtnMouseMoved
        setPanelBackground(InventoryBtn);
    }//GEN-LAST:event_InventoryBtnMouseMoved

    private void InventoryBtnMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_InventoryBtnMouseClicked
        new InventoryNav().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_InventoryBtnMouseClicked

    private void InventoryBtnMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_InventoryBtnMouseExited
        resetPanelBackground(InventoryBtn);
    }//GEN-LAST:event_InventoryBtnMouseExited

    private void BookingsBtnMouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_BookingsBtnMouseMoved
        setPanelBackground(BookingsBtn);
    }//GEN-LAST:event_BookingsBtnMouseMoved

    private void BookingsBtnMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_BookingsBtnMouseClicked
        new Bookings().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_BookingsBtnMouseClicked

    private void BookingsBtnMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_BookingsBtnMouseExited
        resetPanelBackground(BookingsBtn);
    }//GEN-LAST:event_BookingsBtnMouseExited

    private void ClientsBtnMouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ClientsBtnMouseMoved
        setPanelBackground(ClientsBtn);
    }//GEN-LAST:event_ClientsBtnMouseMoved

    private void ClientsBtnMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ClientsBtnMouseClicked
        new Clients().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_ClientsBtnMouseClicked

    private void ClientsBtnMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ClientsBtnMouseExited
        resetPanelBackground(ClientsBtn);
    }//GEN-LAST:event_ClientsBtnMouseExited

    private void SupplierBtnMouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_SupplierBtnMouseMoved
        setPanelBackground(SupplierBtn);
    }//GEN-LAST:event_SupplierBtnMouseMoved

    private void SupplierBtnMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_SupplierBtnMouseClicked
        new Suppliers().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_SupplierBtnMouseClicked

    private void SupplierBtnMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_SupplierBtnMouseExited
        resetPanelBackground(SupplierBtn);
    }//GEN-LAST:event_SupplierBtnMouseExited

    private void VehicleBtnMouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_VehicleBtnMouseMoved
        setPanelBackground(VehicleBtn);
    }//GEN-LAST:event_VehicleBtnMouseMoved

    private void VehicleBtnMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_VehicleBtnMouseClicked
        new Vehicles().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_VehicleBtnMouseClicked

    private void VehicleBtnMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_VehicleBtnMouseExited
        resetPanelBackground(VehicleBtn);
    }//GEN-LAST:event_VehicleBtnMouseExited

    private void StockBtnMouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_StockBtnMouseMoved
        setPanelBackground(StockBtn);
    }//GEN-LAST:event_StockBtnMouseMoved

    private void StockBtnMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_StockBtnMouseClicked
        new StockNav().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_StockBtnMouseClicked

    private void StockBtnMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_StockBtnMouseExited
        resetPanelBackground(StockBtn);
    }//GEN-LAST:event_StockBtnMouseExited

    private void InvoicesBtnMouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_InvoicesBtnMouseMoved
        setPanelBackground(InvoicesBtn);
    }//GEN-LAST:event_InvoicesBtnMouseMoved

    private void InvoicesBtnMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_InvoicesBtnMouseClicked
        new InvoiceNav().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_InvoicesBtnMouseClicked

    private void InvoicesBtnMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_InvoicesBtnMouseExited
        resetPanelBackground(InvoicesBtn);
    }//GEN-LAST:event_InvoicesBtnMouseExited

    private void EstimatesBtnMouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_EstimatesBtnMouseMoved
        setPanelBackground(EstimatesBtn);
    }//GEN-LAST:event_EstimatesBtnMouseMoved

    private void EstimatesBtnMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_EstimatesBtnMouseClicked
        new EstimatesNav().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_EstimatesBtnMouseClicked

    private void EstimatesBtnMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_EstimatesBtnMouseExited
        resetPanelBackground(EstimatesBtn);
    }//GEN-LAST:event_EstimatesBtnMouseExited

    private void PartSalesBtnMouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_PartSalesBtnMouseMoved
        setPanelBackground(PartSalesBtn);
    }//GEN-LAST:event_PartSalesBtnMouseMoved

    private void PartSalesBtnMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_PartSalesBtnMouseClicked
        new PartSalesNav().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_PartSalesBtnMouseClicked

    private void PartSalesBtnMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_PartSalesBtnMouseExited
        resetPanelBackground(PartSalesBtn);
    }//GEN-LAST:event_PartSalesBtnMouseExited

    private void PartsOrderBtnMouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_PartsOrderBtnMouseMoved
        setPanelBackground(PartsOrderBtn);
    }//GEN-LAST:event_PartsOrderBtnMouseMoved

    private void PartsOrderBtnMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_PartsOrderBtnMouseClicked
        new PartsOrderNav().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_PartsOrderBtnMouseClicked

    private void PartsOrderBtnMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_PartsOrderBtnMouseExited
        resetPanelBackground(PartsOrderBtn);
    }//GEN-LAST:event_PartsOrderBtnMouseExited

    private void SettingsBtnMouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_SettingsBtnMouseMoved
        setPanelBackground(SettingsBtn);
    }//GEN-LAST:event_SettingsBtnMouseMoved

    private void SettingsBtnMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_SettingsBtnMouseClicked
        new SettingsNav().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_SettingsBtnMouseClicked

    private void SettingsBtnMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_SettingsBtnMouseExited
        resetPanelBackground(SettingsBtn);
    }//GEN-LAST:event_SettingsBtnMouseExited

    private void SystemServiceBtnMouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_SystemServiceBtnMouseMoved
        setPanelBackground(SystemServiceBtn);
    }//GEN-LAST:event_SystemServiceBtnMouseMoved

    private void SystemServiceBtnMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_SystemServiceBtnMouseClicked
        new SystemServiceNav().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_SystemServiceBtnMouseClicked

    private void SystemServiceBtnMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_SystemServiceBtnMouseExited
        resetPanelBackground(SystemServiceBtn);
    }//GEN-LAST:event_SystemServiceBtnMouseExited

    private void EmailFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_EmailFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_EmailFieldActionPerformed

    private void SearchAreaLblActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SearchAreaLblActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_SearchAreaLblActionPerformed

    private void ExcelExportBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ExcelExportBtnActionPerformed

//        try{
//            JFileChooser jFileChooser = new JFileChooser();
//            jFileChooser.showSaveDialog(this);
//            File saveFile = jFileChooser.getSelectedFile();
//            if(saveFile != null){
//                saveFile = new File(saveFile.toString()+".xlsx");
//                Workbook wb = new XSSFWorkbook();
//                Sheet sheet = wb.createSheet("Open Jobs");
//
//                Row rowCol = sheet.createRow(0);
//                for(int i=0;i<ClientsTbl.getRowCount();i++){
//                    Cell cell = rowCol.createCell(i);
//                    cell.setCellValue(ClientsTbl.getColumnName(i));
//                }
//
//                for(int j=0;j<ClientsTbl.getRowCount();j++){
//                    Row row = sheet.createRow(j+1);
//                    for(int k=0;k<ClientsTbl.getColumnCount();k++){
//                        Cell cell = row.createCell(k);
//                        if(ClientsTbl.getValueAt(j, k)!=null){
//                            cell.setCellValue(ClientsTbl.getValueAt(j, k).toString());
//                        }
//                    }
//                }
//                FileOutputStream out = new FileOutputStream(new File(saveFile.toString()));
//                wb.write(out);
//                wb.close();
//                out.close();
//                openFile(saveFile.toString());
//
//            }else{
//                JOptionPane.showMessageDialog(null, "Error genarated Excel");
//            }
//
//        }catch(FileNotFoundException e){
//            System.out.println(e);
//        } catch (IOException ex) {
//            Logger.getLogger(ClosedJob.class.getName()).log(Level.SEVERE, null, ex);
//        }
    }//GEN-LAST:event_ExcelExportBtnActionPerformed

    private void RegisterClientBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_RegisterClientBtnActionPerformed
        
        if(CustomerNameField.getText().isEmpty() || DateField.getText().isEmpty()){
            JOptionPane.showMessageDialog(this, "Please fill the all area.");
        }else{
            
            String Birthday = SelectBirthMonth.getSelectedItem().toString()+" "+SelectBirthDate.getSelectedItem().toString();
            
            if(Database.saveData("INSERT INTO tbl_client VALUES (default, '"+CustomerNameField.getText()+"' , '"+EmailField.getText()+"' , '"+DateField.getText()+"' , '"+Birthday+"' ,'"+PhoneField.getText()+"' ,'"+SelectHowtoKnow.getSelectedItem().toString()+"' ,'"+AddressField.getText()+"' , '"+pfm.format(new Date())+"' )")){
                JOptionPane.showMessageDialog(rootPane, "Successfully register client.");
                System.out.println("Successfully register client.");
                LoadClientData();
                
                    CustomerNameField.setText("");
                    EmailField.setText("");
                    PhoneField.setText("");
                    AddressField.setText("");
                    
                    GetToday();
                
            }else{
                JOptionPane.showMessageDialog(rootPane, "Error added, please try again.");
            }
            
        }
        
    }//GEN-LAST:event_RegisterClientBtnActionPerformed

    private void ClientsTblMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ClientsTblMouseClicked
        
        DefaultTableModel model = (DefaultTableModel)ClientsTbl.getModel();
        int clienttblindex = ClientsTbl.getSelectedRow();
        ClientidField.setText(model.getValueAt(clienttblindex, 0).toString());
        CustomerNameField.setText(model.getValueAt(clienttblindex, 1).toString());
        EmailField.setText(model.getValueAt(clienttblindex, 2).toString());
//        CostPrice.setText(model.getValueAt(clienttblindex, 3).toString());
        PhoneField.setText(model.getValueAt(clienttblindex, 4).toString());
        DateField.setText(model.getValueAt(clienttblindex, 5).toString());
        AddressField.setText(model.getValueAt(clienttblindex, 6).toString());
        SelectHowtoKnow.setSelectedItem(model.getValueAt(clienttblindex, 7).toString());
        
        String GetBirthday = model.getValueAt(clienttblindex, 3).toString();
        
        if(" ".equals(GetBirthday)){
            
        } else {
            
            String arr = GetBirthday;
            String[] split = arr.split(" ");
//            System.out.println("Name = " + split[0]);
//            System.out.println("Password = " + split[1]);
            SelectBirthMonth.setSelectedItem(split[0]);
            SelectBirthDate.setSelectedItem(split[1]);
            
        }
        
        
        
        
        
    }//GEN-LAST:event_ClientsTblMouseClicked

    private void UpdateClientBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_UpdateClientBtnActionPerformed
        
        if(CustomerNameField.getText().isEmpty() || DateField.getText().isEmpty()){
            JOptionPane.showMessageDialog(this, "Please fill the all area.");
        }else{
            
            String Birthday = SelectBirthMonth.getSelectedItem().toString()+" "+SelectBirthDate.getSelectedItem().toString();
            
            if(Database.saveData("UPDATE tbl_client SET name = '"+CustomerNameField.getText()+"', email = '"+EmailField.getText()+"', idcard_number = '"+Birthday+"', phone_no = '"+PhoneField.getText()+"', how_to_know = '"+SelectHowtoKnow.getSelectedItem().toString()+"', address = '"+AddressField.getText()+"' WHERE client_id = '"+ClientidField.getText()+"' ")){
                JOptionPane.showMessageDialog(rootPane, "Successfully updated client.");
                System.out.println("Successfully updated client.");
                LoadClientData();
                
                    CustomerNameField.setText("");
                    EmailField.setText("");
                    PhoneField.setText("");
                    AddressField.setText("");
                    
                    GetToday();
                
            }else{
                JOptionPane.showMessageDialog(rootPane, "Error updating, please try again.");
            }
            
        }
        
    }//GEN-LAST:event_UpdateClientBtnActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Clients.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Clients.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Clients.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Clients.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Clients().setVisible(true);
            }
        });
    }
    
    public void setLabelBackground(JLabel jl){
        jl.setBackground(new Color(2, 70, 97));
    }
    public void resetLabelBackground(JLabel jl){
        jl.setBackground(new Color(0,87,120));
    }
    
    public void setPanelBackground(JPanel jp){
        jp.setBackground(new Color(2, 70, 97));
        jp.setBorder(BorderFactory.createMatteBorder(0, 0, 4, 0, Color.WHITE));
    }
    public void resetPanelBackground(JPanel jp){
        jp.setBackground(new Color(0,120,167));
        jp.setBorder(BorderFactory.createMatteBorder(0, 0, 0, 0, Color.WHITE));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField AddressField;
    private javax.swing.JPanel BookingsBtn;
    private javax.swing.JButton ClearBtn;
    private javax.swing.JLabel ClientidField;
    private javax.swing.JPanel ClientsBtn;
    private javax.swing.JTable ClientsTbl;
    private javax.swing.JTextField CustomerNameField;
    private javax.swing.JTextField DateField;
    private javax.swing.JTextField EmailField;
    private javax.swing.JPanel EstimatesBtn;
    private javax.swing.JButton ExcelExportBtn;
    private javax.swing.JLabel HomeLbl;
    private javax.swing.JPanel InventoryBtn;
    private javax.swing.JPanel InvoicesBtn;
    private javax.swing.JPanel JobBtn;
    private javax.swing.JLabel LogUserNameLbl;
    private javax.swing.JLabel LogoutLbl;
    private javax.swing.JLabel MenuLbl;
    private javax.swing.JLabel NowDateLbl;
    private javax.swing.JPanel PartSalesBtn;
    private javax.swing.JPanel PartsOrderBtn;
    private javax.swing.JTextField PhoneField;
    private javax.swing.JButton RegisterClientBtn;
    private javax.swing.JTextField SearchAreaLbl;
    private javax.swing.JButton SearchBtn;
    private javax.swing.JComboBox<String> SelectBirthDate;
    private javax.swing.JComboBox<String> SelectBirthMonth;
    private javax.swing.JComboBox<String> SelectHowtoKnow;
    private javax.swing.JPanel SettingsBtn;
    private javax.swing.JPanel StockBtn;
    private javax.swing.JPanel SupplierBtn;
    private javax.swing.JPanel SystemServiceBtn;
    private javax.swing.JPanel TopNavPanel;
    private javax.swing.JButton UpdateClientBtn;
    private javax.swing.JPanel VehicleBtn;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel26;
    private javax.swing.JLabel jLabel27;
    private javax.swing.JLabel jLabel28;
    private javax.swing.JLabel jLabel29;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel30;
    private javax.swing.JLabel jLabel31;
    private javax.swing.JLabel jLabel32;
    private javax.swing.JLabel jLabel33;
    private javax.swing.JLabel jLabel34;
    private javax.swing.JLabel jLabel35;
    private javax.swing.JLabel jLabel36;
    private javax.swing.JLabel jLabel37;
    private javax.swing.JLabel jLabel38;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane3;
    // End of variables declaration//GEN-END:variables
}
